const fontawesome = require('@fortawesome/fontawesome')
const faCopyright = require('@fortawesome/fontawesome-free-regular/faCopyright')
const faBitcoin = require('@fortawesome/fontawesome-free-brands/faBitcoin')
const faEthereum = require('@fortawesome/fontawesome-free-brands/faEthereum')
const faMastodon = require('@fortawesome/fontawesome-free-brands/faMastodon')
const faTwitter = require('@fortawesome/fontawesome-free-brands/faTwitter')
const tags = require('./dm-footer.tag')

fontawesome.library.add(faCopyright)
fontawesome.library.add(faBitcoin)
fontawesome.library.add(faEthereum)
fontawesome.library.add(faMastodon)
fontawesome.library.add(faTwitter)
riot.mount('dm-footer')