version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
jobs:
  build:
    working_directory: /tmp/workspace
    docker:
      - image: circleci/node:12.16.1

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build

      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - dist
  
  deploy-labo:
    working_directory: /tmp/workspace
    docker:
    - image: cimg/python:3.6

    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-s3/sync:
          from: ./dist/
          to: s3://www.labo.danmaid.com/
          arguments: --exact-timestamps --cache-control no-store
          overwrite: true
  
  deploy-production:
    working_directory: /tmp/workspace
    docker:
    - image: cimg/python:3.6

    steps:
      - attach_workspace:
          at: /tmp/workspace
      - aws-s3/sync:
          from: ./dist/
          to: s3://www.danmaid.com/
          arguments: --exact-timestamps --cache-control no-store
          overwrite: true
workflows:
  build-deploy:
    jobs:
      - build
      - deploy-labo:
          requires:
            - build
      - deploy-production:
          type: approval
          requires:
            - build
          filters:
            branches:
              only:
                - master
